# Generated by Django 2.2.12 on 2020-06-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanent_address',
            old_name='H_D_Flat_No',
            new_name='H_D_Flat_No1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='building_apt_name',
            new_name='building_apt_name1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='city',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='landmark',
            new_name='landmark1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='phonoe',
            new_name='phonoe1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='pincode',
            new_name='pincode1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='state',
            new_name='state1',
        ),
        migrations.RenameField(
            model_name='permanent_address',
            old_name='street_colony',
            new_name='street_colony1',
        ),
    ]
