# Generated by Django 2.2.12 on 2020-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200622_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='present_address',
            old_name='H_D_Flat_No',
            new_name='H_D_Flat_No0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='building_apt_name',
            new_name='building_apt_name0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='city',
            new_name='city0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='landmark',
            new_name='landmark0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='phonoe',
            new_name='phonoe0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='pincode',
            new_name='pincode0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='state',
            new_name='state0',
        ),
        migrations.RenameField(
            model_name='present_address',
            old_name='street_colony',
            new_name='street_colony0',
        ),
    ]
