# Generated by Django 2.2.12 on 2020-06-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200622_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='present_address',
            options={'verbose_name': 'Present_address', 'verbose_name_plural': 'Present_addresses'},
        ),
    ]
