# Generated by Django 2.2.12 on 2020-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200622_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associates_address',
            name='phonoe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='associates_address',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='candidate_acceptance_form',
            name='application_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Application ID'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='any_other_deductions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Any Other Deduction'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='anyother_allowences',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anyother'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='basic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Basic'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='cca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CCA'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='conveyance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conveyance'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='cross_income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gross Income'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='da',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DA'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='gross_deduction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gross Deduction'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='hra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HRA'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='lta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LTA'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='medical',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='net_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Net Salary per Annum'),
        ),
        migrations.AlterField(
            model_name='emoluments',
            name='pf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='demo@gmail.com'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_joining_time_required',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Joining Time Required'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_passport_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='passport No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_pp_application_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Application No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_salary_expected',
            field=models.CharField(blank=True, default=True, max_length=100, null=True, verbose_name='Salary Expected'),
        ),
        migrations.AlterField(
            model_name='employee_history',
            name='current_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Salary'),
        ),
        migrations.AlterField(
            model_name='employee_history',
            name='phonoe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='employee_history',
            name='starting_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Starting Salary'),
        ),
        migrations.AlterField(
            model_name='permanent_address',
            name='phonoe1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='permanent_address',
            name='pincode1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='persanal_detail',
            name='employe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='present_address',
            name='phonoe0',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='present_address',
            name='pincode0',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='previous_employment',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='demo@gmail.com'),
        ),
        migrations.AlterField(
            model_name='previous_employment',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Salary Drawn'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='demo@gmail.com'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='phonoe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone No.'),
        ),
    ]
