# Generated by Django 2.2.12 on 2020-06-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200626_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persanal_detail',
            old_name='dob',
            new_name='p_dob',
        ),
        migrations.RenameField(
            model_name='persanal_detail',
            old_name='joining_date',
            new_name='p_joining_date',
        ),
    ]
